# 日本でのデータサイエンス教育の課題にどう向き合うか {#issuesinjp}

> データサイエンス教育一般ではなく、日本の大学において、リテラシー・レベルのデータサイエンス教育をどのように始めていったら良いかに絞って、考えていきたいと思います。

以下は、これまで、わたしが、学び、教え、経験しながら、考えてきたことを基盤としていますが、一般的ではないかもしれないことを、最初にお断りしておきます。

## はじめに

課題をリストする前に、まずは、なぜ、いま、データサイエンスか。さらに、なぜ、すべての人、特に、大学などで学ぶ理系、文系を問わず、学生が、学ばなければならないかを短くまとめると次のようになるとわたしは考えている。

>AI（人工知能）で、**大きく変化しつつある社会**において、ひとびとが、個人で、そして、協力して、どのように生きていくかを考え、準備するために、その背後にある、データサイエンスと、その考え方の基本を学ぶことが必須である。

そして、これに付け加えると、

> 日本は、国や社会のデジタル化、教育機関におけるデータサイエンス教育に関して、非常に**遅れをとっている**と認識されている。

ということだと思います。みなさんは、どう思われますか。

## 課題の整理

1. 教育から学習へ
  - 学ぶことに、中心がなく、教員がわからないことは、学生は学びようがない。
  - 専門から離れられず、**多様性、社会の変化**に適合した、教育になっていない。

2. 世界の課題、人間の課題として、向き合う認識が薄い
  - ローカルな議論に終始することが多く、世界規模の課題に向き合うために、起業したり、世界の一員として活動することに向かわない。
  - ローカルな課題であっても、同じような課題に世界ではどう向き合っているかを考える視点が欠如している。

3. 英語の学習に時間をかけるが使う機会はない
  - 大学においてすら、教員が使わないので、英語を学習に活用する機会がほとんどない
  - 綺麗な英語を話したいなどの願望は、一部にあるが、聞き取りはできず、学習のために、活用することはない

4. コンピュータは、ホームページの検索、閲覧、ワープロとしての利用でとまっている
  - 教員が十分使えないので、学生も趣味の範囲でしか使わない
  - ワープロにちょっと表計算のようなものが限度

5. 携帯端末は、SNS や ゲーム、写真、音楽プレーやどまり
  - 趣味以上のものにはならない

6. 事実や、データを根拠にした、批判的思考になじめない
  - 人格を尊重し、相手に配慮することはたいせつだが、丁寧に、論拠を確認しながら、ここは、ただしいが、ここは間違い、ここは、確認できない、他の視点から考えるなどの訓練がされていない
  
7. 数学を含めて学問が閉じた世界になってしまっている
  - 教員が楽しめることと、実際に使われることとの差が大きい
  - 楽しい、自分にとって有用と思えることしか教えない。一方、学生は、楽しいと思えないもの、自分にとって有用だと思えないことは学ばない
  
8. 時代の変化の中で、教育の中でどう組みたてていくかが考えられない。
  - 教育は、次の世代を担う人たちのためであるはずだが、若い世代の人たちが生きる世界を考えずに教育に携わっている
  - 世の中の変化のスピードが加速しているという考え方は受け入れられない
  
## 学生と、一緒に学び始めませんか

数学者、数学の教育者としてからいったん離れ、ひとりの人間として現実を見つめ、将来について考え、共に学ぶ姿勢をもつ。ここでは、以下の学びに焦点を当てる。

1. AI とどう付き合っていったら良いか経験しながら考える
2. 時間的、地域的、個人的なバイアスから少しでも、自由になるためにデータから学ぶ
3. 多様な、価値観も異なる他者と協力しながら、考え、学ぶ価値を経験を通して学ぶ

このなかで、数学など、自分が学んできたことの価値を考え、活用していくかを、個人として考える

データサイエンスは、これらのために、非常に適した学びだと考えています。具体的な学びについては、第二部で、実際に体験したいと考えています。

## リソースを確認する

1. コンピュータ言語：R、Python など、特に R
  - これらは、世界中のひとの共通語で、国や地域に依存していない
  - 開発も、世界中の人が協力して行っている
  - 利用者は（コンピュータサイエンスの）専門家だけではなく、大きな広がりがある
  - 抽象概念が、パッケージ、モジュール化されて利用できるようになっている
  - Public Domain での共有が一般的
  - コンピュータの進化で、膨大なデータ（Big Data）を活用できるようになっている

2. データの取得 - Big Data and Public Data
  - センサーや、インターネットの発達で、膨大なデータ（Big Data）が時々刻々と集められる、取得できるようになっている
  - Public Data という、人間全体の財産としての、データを適切に共有する動きが、特に国際機関などで進んでいる
  - 世界の中では、この認識に格差もあり、データの利用が十分考えられてない場合もまだある
  
3. 教育、学習コンテンツ
  - 無償または非常に安価に提供されている膨大なコンテンツがある MOOCs (Coursera, edX, Udacity など)、ビジネス化されているものもある
  - 無償まはた非常に安価に、電子書籍などが膨大に出版され、共有されている

4. AI の実用化が進んでいる
  - AI を使った教育が進んでいる。
  - Duolingo のような、無償での利用も可能だが、巨大になっているものもある。
     - We’re here to develop the best education in the world and make it universally available. 私訳：すべてのひとに世界最高の教育を提供することがわたしたちの使命です。
     - Personalized education 一人ひとりそれぞれに相応しい教育の提供
  - Chat GPT が有名ですが、Google 以外に、より複雑な検索を扱う、Perplexity もあり、今後、続々と、特徴的な、AI が公開され、有償だけでなく、無償でも利用できるようになっていくと思われる
  
5. 自動翻訳の進化
  - Google 翻訳は手軽に使え、ある程度実用的に使える段階にある
  - DeepL のように、十分な質と思われる自動翻訳も無償でも提供され、活用できるようになっている。
  - Grammary のように、英語母語話者でも、文章を書く時に使うようになっている、文章校正アプリも質が向上している
  - 電子的に提供されているコンテンツであれば、これらを使うことで、英語に対する、ハードルをかなり下げることができる
  






