# 教養としてのデータサイエンス教育の目的と課題 {#math2020}
## ～MOOCsの活用を視野に入れて～ {-}

> 3 月 12 日 京都数理解析研究所での研究集会「教育数学の一側面 ‒ 高等教育における数学の多様性と 普遍性 ‒ (II)」での講演が covid-19 のため中止となったが、記録として概要を書き残す。本講は、午前中 に予定されたもので、午後の講演予定タイトルは「生涯学び続ける基盤を構築するデータサイエンス・コー スの開発」

最後に、同時期に「数理・データサイエンス・AI（リテラシーレベル）モデルカリキュラム 　～　データ思考の涵養　～（案）」に関する意見として、送付した私見を付記する。

## はじめに

首相官邸発の「 イノベーション政策強化推進のための有識者会議『AI戦略』」[1] では、 2019 年 6 月 11 付けの文書「AI 戦略 2019 ∼ 人・産業・地域・政府全てに AI」で「デジタル社会の基礎知識 (いわゆる『読み・書き・そろばん』的な素養) である『数理・データサイエ ンス・AI』に関する知識・技能、新たな社会の在り方や製品・サービスをデザイン するために必要な基礎力など、持続可能な社会の創り手として必要な力を全ての国民が育み、社会のあらゆる分野で人材が活躍することを目指し、以下の三項目を 2025 年にむけ て実現する目標として掲げている。

1. 文理を問わず、全ての大学・高専生 (約 50 万人卒/年) が、課程にて初級レベルの数 理・データサイエンス・AI を習得 [MOOC 放送大学の活用]

2. 多くの社会人 (約 100 万人/年) が、基本的情報知識と、データサイエンス・AI 等の 実践的活用スキルを習得できる機会をあらゆる手段を用いて提供

3. 大学生、社会人に対するリベラルアーツ教育の充実 (一面的なデータ解析の結果や AI を鵜呑みにしないための批判的思考力の養成も含む)

現在の日本の就業労働人口が約 6 千万人、その 25%の 1500 万人が「『数理・データサイエ ンス・AI』に関する知識・技能、新たな社会の在り方や製品・サービスをデザインするた めに必要な基礎力」を持つことを目標としている。産業界が中心に、社会人(100 万人/ 年)計画が推し進められるものと思われ、すでにいくつかのプログラムがスタートしている^[5 月 20 日から 22 日に開催される、第 11 回 教育 IT ソリューション EXPO においては、教育プログラムが商品化され、宣伝されると思われる。大学によっては、このような企業と契約を結び、プログラムを提供してもらうところも現れると思われるが、産業界での動きや、基本技術については得られるかもしれないが、大学教育には、担うべき責任が他にあると考え本稿を書いている。]。
大学・高専では「数理・データサイエンス強化方策」のもとで定められた拠点校 6 校と協力大学・コンソーシアムを中心に現在モデルカリキュラムの作成が行われ、さらに
「国内大学等において実施されている AI 等教育プログラムの主な事例」[3] が集められている。2000 年の廣中レポート^[22000.6 学生の立場に立った大学づくりを目指して(廣中レポート)]、GP プログラム選定から始まった、大学の教学改革を彷 彿とさせる勢いである^[今回は首相官邸発である点も特徴的である。]。

その一つの到着点が主体的学習などが中心に置かれた、2012 年の中央教育審議会答申^[42012.8 新たな未来を築くための大学教育の質的転換に向けて ∼ 生涯学び続け、主体的に考える力を育
成する大学へ] と考えると、小中高で始まっている統計教育 [4]、コンピュータ教育、英語教育、大学入学試験改革や、STEAM 教育の重要性など、教育内容の改編が、大学・高専に到達したと言えるかもしれない。上の 1, 3 が大学教育の中に組み込まれていくなかで、大学教育(以後、この言葉で高専も含むものとする)における位置づけと、その内容について考える上で、まずは「数理・データサイエンス・AI」という言葉で表現されているものの内容を確認するとともに、その目的とわが国の大学教育における課題について考察したい。「データサイエンス・AI」という言葉に代表される専門領域に精通しているわけではないが、文理を問わず、学生全員が必修として学ぶと言うことだけでも大きなインパクトを持つものである。また大学に於いて教養教育は様々な形で語られてきてはいるものの「リベラルアーツ教育の充実」という文脈で「数理」とその応用をどう捕らえたらよいのか、この問いは、大学での教育に関わって以来、常に考えてきたので、その点を中心に考察する。

## データサイエンス

本稿の表題には「データサイエンス」という用語を用いているが、首相官邸から発せられた文書は「AI 戦略」となっており、文部科学省では「数理・データサイエンス」の名称が使われてきたが、2019 年度から AI が加わり「数理・データサイエンス・AI」となっている。初等中等教育では「統計」教育の充実が進められてきた経緯からも、数理、データサイエンス、AI と統計、これらの言葉をどう理解し、大学教育を整備していくかを整理する必要があると思う。

しかし、実際のところ、これらの言葉を明確に定義し、区別し、関係性を明確にすることは困難である。AI (Artificial Intelligence(人工知能)は学問の専門領域を現す言葉としてもとれるが「AI戦略 2019 ∼ 人・産業・地域・政府全てに AI」で表現されているものは、それとは方向性が異なるであろう。また最近のメディアで使われている「AI によって、AI が組み込まれて」などの言葉は、学問的な問いとしてではなく、これらの言葉を利用することで、ブラックボックス化して、中身については問わないものとしているようである。AI の社会的影響が甚大であることを考えると、ブラックボックス化は、思考停止を招いており、教育においては、それこそが問われなければいけないだろう。

また、これだけ注目されてきている背景には、インターネットの発達と、経済活動の国際化、また人口の増大とともに、国際的な人の移動が活発になり、人間の活動が、地球規模での気候変動にも影響を与えるという人間社会の未曾有の変化に対応するために注目されていることも見逃してはならない。これらからひきおこされる、感染症の世界的蔓延、極度の貧困・貧富の差や、フェイクニュースやヘイトスピーチが生み出す世界の分断・紛争、原因・責任が複雑で明確にできない経済危機にも、立ち向かって行かなければならない。さらに、この分野において、日本が遅れており、このままでは、世界から取り残される可能性が高いという危機感もあるだろう。遅れているとすると、その原因は何な
のか。この背景を理解しなければ、表面的な対応となり、本質的な改善は期待できないと思われる。([11] 参照)

データサイエンスの明確な定義は、確立していないが、短く表現すると「データを活用して課題を発見・探求し、適切な解決策を探る科学」で、意思決定のための科学(Decision Science)とも表現できる。また、エンピリカル(Empirical Study)と言われるように、理論ではなく、実験(実証,経験)に基づいた分野でもある。必然的にコンピュータを利用し(課題に応じ)様々な分野のひとたちと協力することが不可欠な学際科学であるとともに、解決策を探るには数理モデルを適用し・機械学習で評価し・アルゴリズムを策定する数理的思考、その共有、可視化などわかりやすい説明によるコミュニケーションが不可欠である。この課題解決の全体のプロセスを「AI を使って課題を解決する」とも表現する。 活用可能な範囲は、意思決定のための科学という観点からは、ほとんどすべての分野としか表現できないが、手書きの郵便番号の認識に始まり、音声認識、顔などの画像認識へと進み、現在注目を集めているものとしては、Google, Amazon, Netflix などのリコメンダ・システム(Recommendation System)、診断・投薬管理・治療方法といった、医療システムの開発、法律・財務、その他の相談業務、国や公共機関の政策決定、犯罪捜査、防犯システム、災害予知、防災などが挙げられるだろう。

効果とその影響についても、考える必要がある。有効性としては、課題解決のための、阻害要因を精査して、目的を達成できる可能性、効率が高い選択肢を、見つけ出すことが可能である。同時に、適用範囲が広く、社会的影響が大きく、社会的責任・倫理問題が増大することもあり、一部はすでに社会問題化している^[日本ではまだ散見される程度であるが、米国などでは、大統領選挙にも関わる様々な課題として似認識され始めている。([7, 9] 参照)]。しかし、データに基づいた根拠を求め、思考する訓練は、フェイクニュースやヘイトスピーチなどに惑わされず、個々の課題に個人がどう向き合うかという、民主的な、多文化共生の社会基盤を生み出す可能性を秘めていると同時に、多くの人たちが「AI に任せる」「AI が答えを出したのだから」と、個人で考えなくなる可能性も秘め、教育により新たな分断を生み出す危険性もある。また、データを根拠とすることは、数値化しやすい価値が強調され単純な功利主義的な判断が優先され、公平・尊厳・人権・倫理・感情・共感・文化など、数値化が困難ではあるが、ひとにとって本質的なことが置き去りにされないためには、どのような配慮、方策、制度、法律などが必要かも、検討する必要がある。膨大な、データから判断すること自体が、客観的で価値が高いように思われるが、おそらく人間には、理解しづらいことで、納得感、安心感などが、失われる可能性も十分にあり、母集団をいくつかの因子からではなくトータルにみる視点を意識して育むことも必須である。([12] 参照)

個人的には、特に大学教育においては「データサイエンス」を用語として中心的に使うことが望ましいと考えている。深い数理的思考は、実際の探求過程において、必要不可欠であるが、専門分野によって分断がおこりやすい高等教育機関においては、すべてのひとが協力して課題を発見、特定し、ひとり一人への影響を考慮しながら解決を探る学際的な分野であることを強調すべきである。統計学は、データサイエンスの理論的基盤を支えるものであるが、統計学では完結しない範囲に関わることから、実際の学びの中で、背景にある統計の考え方を少しずつ学んで行くことが適切である。

AI については、すでに述べたが、ブラックボックス化して、応用から得られる限られた評価基準での効率・利得を強調しすぎることなく、脳の働きを含めた、思考するとは、学ぶとはという基本的な、ひとの営み、また、そのある部分を実装する研究など、人工知能の研究は、経済活動や単なる技術などとは、独立にも進んで行くべきものである。特定のことに特化して力を発揮する AI の開発から、現在は、複合的な問題を取り扱う AI へと進んでおり、将来的には、Artificial General Intelligence (AGI) と呼ばれる、人間の脳の働きのような、一般的な問題を取り扱うことが少しずつ可能になっていくであろう。「AI が考えた」ことの背景を分解して説明し共有し、適切な選択肢を共に選び取っていこうとする人材を育てることこそが、AIを活用する人材を育む高等教育機関の責任ではないだろうか。人間とは何者で、これから世界はどのように変化して行くのだろうか。

## 大学教育における課題

前節で課題の概要についてもふれたが、大学教育においては特に、どのような学生の育成をめざすかを明確にしながら教育課程を構築すること、学際科学として最終的には大学全体としての関わり方、数理分野の教員の教育への関わりかた、このためのコストとインフラ整備に関するビジョンを明確にすることについて以下に述べる。

### どのような学生を育成するか 

まず、私論であるが、データサイエンス教育の目的を短い文章で表現すると以下のように
なる。

> 現今の産業や経済活動を含む人間社会の国際的な変動が、ひとり一人の活動と影響し合っていることを理解し、生涯学び続けながら、データに基づいて課題を探求するひとを育成することを目的とする。

変化の時代に生きていくためには、先人の英知を蓄積することに留まらず、それをどう活用していくか、生涯学びつづける基盤を得ることを中心におくことが肝要である。常に生成されている膨大なデータを、インターネットを介して入手することができ(IoT, Big Data)、コンピュータを使って、分析し、可視化して理解し、他者と共有し、適切な解決方法を探索する道筋を理解し経験することで、課題と向き合う社会の責任ある構成員となることを支援することが教育機関の使命であると考える。

データサイエンス自体が、理論ではなく、データに基づいて課題を探求する実証的な新しい科学であることを理解し、関連する分野の広がりを認識しながら、他者とも協力して、いくつかの課題に興味を持って、実際に取り組みながら、影響する範囲と具体的な課題を議論し、さらに学んでいく手段をイメージできるようにすることが肝要である。

公開データ(Public Data)の活用、分析・探索プロセスの大まかな理解とともに、機械学習などで有効性が高いと評価された方策の課題を具体例も含め、学生自身が調べ、積極的に議論する経験も必要である。

英語の活用も有効である^[20年ぐらいの内には、中国語の存在感も増大すると思われる。国際会議や、国際的な経済活動において、現在は英語が使われることが多いが、分野によっては、実際の議論は中国語でされることが広がっている。データサイエンスやコンピュータ科学、経済分野では、インドとともに、中国の存在は、顕在化している。]。高校までで十分な時間をかけて英語を学んでいながら、大学で殆ど活用されていないが、データサイエンス教育は適切な突破口になると思われる。英語を活用することで入手できるデータが莫大で広範囲となるとともに、無償で提供されている分析ツール(R, Python など)を利用でき、そのユーザコミュニティでの共通言語は英語が中心、edX, Coursera, JMOOC などの MOOCs をはじめとして、インターネット上で、無償の学びの場も、英語では、膨大に存在することを実際に使ってみながら経験するこが可能である。世界の状況を垣間見れば、日本の状況がどのようなもので、英語を活用すれば、学びの機会がどれほど広がるかを学生の間に経験して欲しい。国際連合や、世界銀行などのデータの活用も、世界の一員として自覚を持って自己の生き方を見つめるよい機会となると思う。データは数字であることが多く、この分野の英語も難しくはない。英語を活用して学ぶ良いステップである。

また、経済格差が、教育格差となることを避けつつ、生涯を通して、学びたいとき、必要なときに学ぶことができる基盤を構築することも配慮すべきであり、この意味でも、データサイエンス教育において、無償のオンラインの学びを促進することは価値が高い。

前節でデータサイエンスについて記述したことからも理解できるように、データサイエンスには、様々な視点が必要である。いろいろなところで引用されている、‘Skills and Self - ID Top Factors’ [13] にもあるように、データサイエンスには、様々な技能や視点が必要であり、それを一人で賄うことは、不可能であり、課題によってまた分野によって、必要なスキルを、互いに補い合い、その過程で欠けている視点や、能力を認識する必要がある。([8] 参照)すなわち、データサイエンスで必要な技能をひとりで充足させることはできず、GAFA などでは常識となっているが、様々な分野の人たちが協力するチームでの活動が重要でもある。その中で、理系・文系をとわず、どのような学びが鍵となるかを 学ぶ経験も重要な資産となる可能性が高い。

### 全学がどう関わるか

特定の分野の学習が全学必修になるという、大学教育においては、近年には経験したことがない状況と、大学全体として、まずは真摯に向き合うことが必要である。中心的な課題とは離れるので、ここで書いておくが、大学院生も分野を問わず、履修または聴講できるようにすること、TA も他のクラスを積極的に聴講できるようにし、関係する TA 同志で議論し、授業の改善を提案できるようにしておくことが重要である。実習を加えることが欠かせないとすると、だれでも担当できるわけではないが、極力広い専門分野の大学院生が関わることができるようにすることが望ましく、受講生にとっても望ましいと思われる。また、すでに受講している学部学生も、技術的なサポートなどとしては、アルバイトとして関わることも検討することも良いと思われる。経験のある専任教員では担当を賄い得ない背景で、全学としてきめ細かなサポート体制を構築することは成否を分ける課題である。

さて、2025年、今から 5 年後、すべての大学および高専卒業生が「『数理・データサイエンス・AI』に関する知識・技能、新たな社会の在り方や製品・サービスをデザインするために必要な基礎力」を獲得して、卒業していったとしよう。大学教員はどうだろうか。それぞれの学問分野においても、学生が学んだことを理解できない教員で溢れることはないだろうか。もし、それが「持続可能な社会の創り手として必要な力」であるなら、当然、大学教員、そしておそらく職員にとっても、必要な力であるはずである。すぐに、教えることはできないだろうし、それには、膨大なエネルギーを必要とし、失うことも多いだろう。しかし、複数の教員が学生と共に学ぶことは、可能であるはずである。そして、担当教員も少しずつ学ぶ姿は、学生にとっても、刺激となる。数学・コンピュータ・英語が不得意で(またはそう思い込んでいて)、学ぶことを拒否してしまうことは、学生にも、教員にも、職員にもあることだが、共に乗り越える経験とともに、それぞれの専門分野からの異なる視点や、経験からの阻害要因の指摘、バイアスの認識や指摘など、お互いに学ぶことは多い。

社会科学系、人文系であっても、統計を使う分野は多いが、多くの場合、その分野の専門性の高いソフトを使うことが多い。そのまま紹介してもらうことも良いかもしれないが、R のような、パブリックドメインの Free なソフトでも、基本的な部分はできること を経験してらもうように、技術スタッフまたは、サポートの大学院生などが、変換の手伝いをすることは、有効である。研究者は、自分の研究に適したソフトを選択するが、学生は、有償のソフトは、各大学・研究室でサポートしていたとしても、卒業後は使えないからである。また、研究者も、より広い分野とのつながりを得ることができる可能性もある。学際的な学びのメリットでもある。

すぐに、すべての教員がデータサイエンス教育に関わることは、様々な理由から困難であろうが、上に述べた理由からも、基本的に、専任教員全員が何年か(たとえば最低三回)は担当するなどを決めることで、全学的な取り組みとすることが可能になる。シラバスと、コーディネータ、さらに、途中でも、相談に乗れる、チームを別途用意することも、不可欠であろう。

「数理・データサイエンス・AI」教育の推進が、文系と理系のさらなる分断が起こらないように、特別に配慮する必要がある。それを、軽減して、お互いに、Respect をもって、教育にあたることのできる、すばらしい機会だと思う。

### 数理分野の教員の関わり方に関する課題

数理分野をどう特定するか困難であるが、データサイエンスに関わることを考えると、本来は、統計学が重要であるが、日本では、まだ独立した分野と見なされていない面もあるので、ここでは、数学(統計分野を含む)、情報を中心に理系分野を想定するものとする。個人的に、現在は、定年退職して、関わっていないが、大学での数学教員を長くしてきたこともあり、数学を中心に考えてしまうことは、お許し願う。

最初に注意すべき事は、担当教員も学生と共に、少しずつ学ぶことをこころがけるとともに、数学・コンピュータ・英語が不得意で(またはそう思い込んでいて)、学ぶことを拒否してしまう学生に、配慮することである。不得手だと感じているものを、学ぶことは、誰にとっても苦痛である。

### コストとインフラ整備 

以下の提案をする。

1. Broad Band の Internet Access を公共インフラとして、無償または低価格で提供。経済的格差が教育格差、経済的格差の固定化とならないように、学習機会の公平化をめざし、Broad Band での Internet Access が、提供されることを要望する。

2. RStudio (for R), Jupyter (for python) などの基本的なサーバーを、どこからでも、だれでも利用できるように、日本語環境も整備しながら、提供する。Data Science をはじめとした、学習・教育を支援するための Interactive な学習ツール開発などには、サーバーが必要であり、Security などの面から、信頼できる機関が、管理運営することが必要である。

3. 分野の異なる、特に、文系の教員と理系の教員、社会科学系の複数の教員が、共同で学びながら、教える、Team and Collaborative Teaching を推進するため、このような枠組みについては、特別の補助を、文部科学省の予算枠内ではなく、官邸の特別補助枠を用いて、行うことを要望する。学際科学の推進のためには、教員の教育学習が必須であり、共働で学び、考え、教える、経験のための、経済的支援が必要である。パイを拡大しないと不可能である。

4. 大学が、一般のひとの学びを支援するため、MOOCs や、OCW その他、質の高い、教育・学習コンテンツを無償で、提供できるように、支援する。初期においては、その質の向上も目指して、大学・高専の職員も、受講できる枠組みを作るべきである。Interactive な教材で学ぶなど、また、考える機会を重視するなど、日本のその方向での学習環境提供の質は、高くない。海外からも、一般の教員などが、学べる環境を、提供し、科学研究費受給者であっても、教育の質の改善のための、研究補助金を受けることができるようにする。

5. 政府・行政機関や、公共性の高い企業が、積極的にデータを使いやすい形式で公開し、データ分析に依拠した情報を、可視化してわかりやすく伝えるモデルを意識した情報公開をし、メディアにも、Fact Base, Evidence Base というに留まらず、データに依拠し、適切な可視化をともなった情報伝達を促し、奨励することを要望する。特に、AI の活用においても、極力、Black Box 化をさけ、どのようなデータを用いているかなどを伝える努力をうながす。Fake News、Hate Speach、風評被害などを、極力抑えるために、有効な、事実とデータに基づいた情報提供を適切に行う。政府公共団体の首長、職員や、政治家の勉強会提供も、必要であろう。このことは、Data Sciece を学んだ学生たちの就職の道が広がr区事にもつながり、大学などでの学習意欲の向上にも資する。

Learning Goals 

* A. Data Science: What? and Why? 
  - Data Science とは? 統計・ AI ? Data Scientists? 
  - Data Science が注目される背景? - 変化
* B. Business の世界に おける Data Science 
* C. Data Science と社会:Data から見る世界、Data をもとにした 思考
* D. Data Analysis 入門

## おわりに References

[1] イノベーション政策強化推進のための有識者会議「[AI戦略](https://www8.cao.go.jp/cstp/ai/index.html)」(AI戦略実行会議) 

[2] 「[AI 戦略 2019 ∼ 人・産業・地域・政府全てに AI](https://www5.cao.go.jp/keizai-shimon/kaigi/special/reform/wg7/20191101/shiryou1.pdf)」2019 年 6 月 11 日  

[3] [国内大学等において実施されている AI 等教育プログラムの主な事例](https://www8.cao.go.jp/cstp/ai/suuri/r1_1kai/r1_1kai.html) 

[4] 「[統計について学ぼう](https://www.mhlw.go.jp/toukei/learning/index.html)」厚生労働省サイト 

[5] 文部科学省：[数理・データサイエンス・ＡＩ教育プログラム認定制度（リテラシーレベル）](https://www.mext.go.jp/a_menu/koutou/suuri_datascience_ai/00002.htm)

[6] 鈴木寛「[教養としてのデータ・サイエンス教育 ~ Moocs の活用を視野に入れて](https://icu-hsuzuki.github.io/science/index-j.html#msj2019)」日本数学会教育委員会シンポジウム(於:金沢大学)

[7] AUTOMATE THIS: how algorithm came to rule our world by Christopher Steiner（[WikipediA](https://en.wikipedia.org/wiki/Automate_This)）、 邦訳「アルゴリズムが世界を支配する」[出版社情報](https://www.kadokawa.co.jp/product/321306000181/)

[8] Doing Data Science by Rachel Schutt and Cathy O’Neil [Publisher's Site](https://www.oreilly.com/library/view/doing-data-science/9781449363871/)、邦訳「データサイエンス 講義」[出版社情報](https://www.oreilly.co.jp/books/9784873117010/)

[9] Weapon’s of Math Destruction by Cathy O’Neil [WikipediA](https://en.wikipedia.org/wiki/Weapons_of_Math_Destruction), [Review: Scientific American](https://blogs.scientificamerican.com/roots-of-unity/review-weapons-of-math-destruction/)、邦訳「あなたを支配し、社会を破壊する、AI・ビッグデータの罠」[出版社情報](http://www.intershift.jp/w_aibg.html)

[10] [edX Professional Certificate in Data Science](https://online-learning.harvard.edu/series/professional-certificate-data-science),  [edX Data Science Ethics](https://www.edx.org/course/data-science-ethics)

[11] Factfulness by Hans Rosling, et. al. [Gapminder](https://www.gapminder.org/factfulness-book/), [WikipediA](https://en.wikipedia.org/wiki/Factfulness:_Ten_Reasons_We%27re_Wrong_About_the_World_–_and_Why_Things_Are_Better_Than_You_Think) 邦訳「ファクトフルネス」[出版社情報](https://bookplus.nikkei.com/atcl/catalog/19/P89600/)

[12] How I learned to understand the world by Hans Rosling with Fanny Haergestam [Book Information](https://us.macmillan.com/books/9781250266903/howilearnedtounderstandtheworld)、邦訳「私はこうして世界を理解できるようになった」[出版社情報](http://www.seidosha.co.jp/book/index.php?id=3351)

[13] Analyzing the Analyzers (O’Reilly) by Harlan Harris, Sean Murphy, and Marck Vais- man [Publisher's Site](https://www.oreilly.com/library/view/analyzing-the-analyzers/9781449368388/)


## 参考：モデルカリキュラム （リテラシーレベル）案に関する意見

以下は、「数理・データサイエンス・AI（リテラシーレベル）モデルカリキュラム 　～　データ思考の 涵養　～（案）」に関する意見 に対して、送付した意見である。参考に付す。（2020年3月）

> HP: http://www.mi.u-tokyo.ac.jp/consortium/mc_literacy.html
提出様式：記載内容：①所属機関・部署名、②氏名、③連絡先（メールアドレス等）、④該当箇所、⑤意見

> 数理・データサイエンス教育強化拠点コンソーシアム

### （[案](http://www.mi.u-tokyo.ac.jp/consortium/pdf/model_curriculum.pdf)）に対する私見

- タイトル：
	- データ思考の涵養：すばらしい、特にリテラシーレベルで最初に取り組むべき事
- 概要部分（表紙の次の表を伴ったページ）
- 人間中心の適切な判断ができ、不安なく自らの意志でAI等の恩恵を享受し、これらを説明し、活用できるようになること。
	- 「人間中心」の意味を明確化する必要がある。（AI社会原則をていねいに理解する必要がある）
- 数理・データサイエンス・AIを活用することが 「好き」な人材を育成し、それが自分・他人を含めて、次の学修への意欲、動機付けになるような「学びの相乗効果」を生み出すことを狙う。
	- 教育課程において、「楽しさ」は必須で、「学ぶことの意義」を重点として教えることには大賛成だが、「数理・データサイエンス・AIを活用することが 『好き』な人材を育成」することが目的ではない。おそらく、「それが自分・他人を含めて、次の学修への意欲、動機付けになるような「学びの相乗効果」を生み出すことを狙う。」へと続くために「好き」があるのだと思うが、適切ではないとおもう。「それが自分・他人を含めて、」の部分は不明。
	- それぞれの分野での学びに結びつけることを意図している点は、その通りだと思う。
- モデルカリキュラムと教育方法
	- 適切なことが書かれているが、カリキュラム運営体制として、理系文系など、複数の教員が協力して教える体制を強調すべき。特に、理系の教員が中心であれば、「人間中心」や「実社会の課題」と適切に、向き合うことは困難。
	- 「実際に手を動かしてデータを可視化する等、学生自身がデータ利活用プロセ スの一部を体験できることが望ましい。」が重要で、座学では、自ら学ぶこと、さらに「データ思考の涵養」にはつながらない。MOOCs など、Online 教材を、このためにも、有効利用すべきである。良い教材は、英語のものが殆どであるが。特に、早い時期に、英語でも学ぶ機会をえることは重要。英語の学びや、入試に英語があることは、そのためであるとも言える。学生のレベルにあわせ、支援を十分しつつ、教員も含めて、共に学ぶ経験を生かすべき。
	- 四つ目の枠の内容が不明確であるが、早い時期から、たとえ、十分な質になっていなくても、授業を極力公開し、利活用できるように、すべきである。日本は、OCW, MOOCs など、極度に遅れており、それは、実際の講義などが公開されないために、質の向上が目指せないことが背景にある。公開されることで、教職員も学ぶことができ、他の大学の授業からもアイディをえることができる。それをまとめて紹介するようなサイトができればさらに良い。全学必修で、新しい内容のコース、かつ学際的な内容を含むものは、教員も手探りである。積極的な公開を促すことが肝要。
- P.5 なお、各大学・高専において、数理・データサイエンス・AIのリテラシーレベルの教育カリキュラムの検討、実施にあ たっては、オンライン教材や民間企業等(スタートアップを含む。)が開発・提供する教材の活用を含め、他大学、民間企 業等の優れた取組を大いに参考とし、活用することを奨励する。
	- ツールとして統計ソフトを活用するレベルは、民間企業などの教材も有効であろうが、大学・高専でまなぶべきことは何なのかをふまえた、記述をするべき。社会人 1500万人の教育も進むなかで、大学・高専では、データ応用技術を学ぶことが中心ではないことを明確にすべき。
	- 実際の分析にすこしでも関わることは、データ（数値）を見てもほとんど意味はわからない。また、あるグラフを見ただけでは、グラフ作成者の意図のもとで、データをみることになり、一方的な解釈を理解するしかできない。同じデータから、どんなことを見ることができるか、グループ活動もとおし、様々な見方を実際にこころみることが必須。ダッシュボードを用いて、自分で操作することも、そのいみで多少の利点があるが、それも、ある枠内での、解釈であり、その、ダッシュボードの内容を自分でも得ることができる経験を持つことが必要。そして、それは、可能だと考える。
- P.9 データ・AIを活用することによって、どのような価値が生まれているかを知る
	- このためには、自分でいくつかのデータから読み取れることを操作しながら、考える必要がある。
	- 教員が、すべて理解できるわけではなく、学生と共に学ぶ姿勢が特に必要。数学の基礎教育との大きな違いがここにある。
- P.10 社会におけるデータ・AI利活用
	- それぞれの活用がどのようになされているか、データがどう使われているかの内容が提示されないと、単なるブラックボックス的AIから逃れられない。それが、自分達が作業している、データの取り扱いの延長線上にあることを認識できる工夫が必要。そこまで踏み込んだ、内容の授業を共有できることが望ましい。（全員がこのレベルの授業をできるわけではないので）
- P.11 スプレッドシート等を使って、小規模データ(数百件~数千件レベル)を集計・加工できる
	- 作業を記録、再現できるように指導することが重要。共有も可能になる。
- P.12 2. データリテラシー<スキルセット>
	- 高校までの学びの確認、適切な連携も必要。むろん、全員が理解できているわけではない。
- P.13 3. データ・AI利活用における留意事項
	- この段階で、どの程度理解できるか不明。社会における利活用と、絡ませることができるかが、鍵であるとともに、あまり、データ活用から離れないような注意も必要。
- P.19 数理・データサイエンス・AI リテラシーレベルの教育方法
	- 1. 社会におけるデータ・AI利活用：導入としては可能かつ適切だと思う。
	- 2. データリテラシー：ここが困難。Excel や、Google Spread Sheet のレベルだと、知っている人と、知らない人で、大きな差が生じ、何も学ばない学生が生じる。個人的には、RStuio.cloud または、公的機関が提供する、RStudio Server 上で行うことが望ましい。基本学習とともに、いくらでも発展が可能。
- P.20 1.講義・演習等による授業上の工夫
	- 「身近な活 用事例や社会の実データ・実課題を用いた演習」この選択が可否を決定する。分野の異なる複数の教員が話し合い、学生からも案を出させること、TA などのアイディアも適切に用いること、インターネット上で、共有・公開・蓄積することが望まれる。
	- 「実務家教員の活用や、地方自治体や企業・団体と連携した取組」とあるが、卒業生が実際に関わっていることの紹介は、学生には特に有効。他大学であっても、卒業後、数年から10年程度、若い卒業生による事例紹介は有効
- P.21 2.オンラインプログラムの導入
	- 有効であるが、問題は、Exercise の質である。これによって、受講生が真剣に取り組むかどうかが変化する。
	- 残念ながら、この質が高いものが、日本には少ないと思われる。英語での教材を使うことは、積極的に考えるべき。
- P.23 3.外部機関のオンラインコンテンツを授業で活用
	- 必要なことであるが、ノウハウを十分持っている教員、機関、大学が少ないと思われる。
	- 海外のMOOCs は質の高い Exercise を提供するものも多いので、修了証受領と、まとめのテスト、または、レポート提出などの複合型を、開発し、共有することが望まれる。
- P.24 4.他大学における学修を単位認定(単位互換等)
	- 海外の MOOCs 活用を奨励するため、修了証を得た場合は、レポート提出を課すことで、単位として認めるようなことも積極的に勧めるべき。
- P.27 2.モデルカリキュラム策定を受けた各分科会との連携・検討
	- 一つ一つが共有され、推進がチェックされる状況を作ることが必要
	- 海外のものを積極的に学び、取り入れることをしなければ、日本は現在そうであるように、今後も、後陣を拝する。
	- 海外でも、優秀なコンテンツは、それほど多くないと思われるので、それらを取り入れると共に、連携をはかることも有用
	- 進展が速い分野でもあり、翻訳などを進めるのは、結局、データサイエンス推進を遅らせる。

### 日本の教育の遅れに関する認識
- 学際科学分野、特に、理系文系の融合分野が遅れている、それにともない、異分野の教員の教育における協力体制未発達
- 批判的に考え、意思決定の根拠を他者にも理解できるように説明しながら学ぶリベラルアーツ教育が未発達
- 文理の分断がとくに高校以降の教育現場で激しく、文系の学生には、理系アレルギーまたは数学への恐怖心が強い学生が多く、理系の学生には、社会の問題と大学で学ぶことの関係の認識が希薄
- コンピュータ教育がなされておらず、コンピュータは、ホームページ閲覧とワープロとしての利用が殆ど
- 社会、政府、メディアなどにおいて、データおよび、その可視化（Visualization）によるコミュニケーションの重要性が認識不足
- 授業などの公開（OCW）が未発達な中で、MOOCs を一部始めているが、非常に限定的、教育方法を学ぶことも遅れている
- 教育から学習へという視点への移行が遅れ、（数理系では学問の性質上顕著に）学生と共に学ぶ経験が少ない
- 英語で学ぶことが限定的で、世界に目が開かれておらず、世界から学ぶ姿勢が欠如している
- 海外での教育から学ぶことができておらず、大学教育において顕著

### 良いととることができる面もある
- 単純な功利主義（naive utilitarianism）に対する抵抗が強く、株式をはじめとして、AIでのコントロールに消極的である
- 過度な自己主張を嫌い、協力、チームワークがだいじにされる。（個性や多様性を生かすチームでの働きは遅れている）
- 小中学校での、基礎教育は世界的にもある程度の水準を保っており、ある程度、仮定できる基礎学力もある